bookstore/urls.py
from django.urls import path
from .import views

app_name = 'books'

urlpatterns = [
    path('booklist',views.home),
    path('book-details/<str:id>',views.detail,name='book-details')
]

djangodb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include('bookstore.urls'))
]

bookstore/models.py
from django.db import models
from django.db.models.base import Model
from django.utils.text import slugify

from django.core.validators import MaxValueValidator,MinValueValidator


# Create your models here.   


class Country(models.Model):
    cname = models.CharField(max_length=50)
    code = models.CharField(max_length=50)

class Address(models.Model):
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)

    class Meta:
        verbose_name_plural='Author_Address'

    def __str__(self):
        return f'{self.street} {self.city} {self.pincode}'
    
class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    address = models.OneToOneField('Address',on_delete=models.CASCADE,null=True)

    def __str__(self):
        return f'{self.firstname} {self.lastname} {self.address}'


class bookdata(models.Model):
    bname = models.CharField(max_length=50)             
    category = models.CharField(max_length=20)       
    # author = models.CharField(max_length=50)
    author = models.ForeignKey('Author',on_delete=models.CASCADE,null=True,related_name='book')
    price = models.IntegerField()
    best_seller = models.BooleanField(default=False)    
    ratings = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(10)],null=True)
    slug = models.SlugField(default="",null=False)
    published_country = models.ManyToManyField('country')

    def __str__(self):
        return f"{self.bname} {self.author} {self.price} {self.best_seller}"       

    def save(self,*args,**kwargs):
        self.slug = slugify(self.bname)
        super().save(*args,**kwargs)
                                 

bookstore/views.py
from django.shortcuts import render
from .models import bookdata
from django.http import HttpResponseNotFound

# Create your views here.

def home(request):
    b=bookdata.objects.all()
    return render(request,'bookstore/home.html',{'books':b})

def detail(request,id):
    try:
        d=bookdata.objects.get(pk=id)  #slug
        return render(request,"bookstore/details.html",{
            'title':d.bname,
            'category':d.category,
            'author':d.author,
            'price':d.price,
            'best_seller':d.best_seller,
            'ratings':d.ratings

        })
    
    except:
        return HttpResponseNotFound("Invalid Book Request")

bookstore/templates/bookstore/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

bookstore/templates/bookstore/details.html
{% extends "bookstore/base.html" %}

{% block title %}BookDetails{% endblock title %}

{% block content %}
    <center>
        <ul>
            <li>Title:{{title}}</li>
            <li>Category:{{category}}</li>
            <li>Price:{{price}}</li>
            <li>Author:{{author}}</li>
            <li>Ratings:{{ratings}}</li>
            {% if best_seller %}
                <h6 style="color:green">Is Best Seller</h6>
            {% endif %}
        </ul>
    </center>
{% endblock content %}
    

bookstore/templates/bookstore/home.html
{% extends "bookstore/base.html" %}
{% block title %} Home {% endblock title %}

{% block content %}
    {% for i in books %}
        <ul>
            <li><a href="{% url "books:book-details" i.id %}">{{i.slug}}</a></li>
        </ul>
    {% endfor %}
{% endblock content %}